openapi: 3.0.0
servers:
  - url: 'https://virtserver.swaggerhub.com/MyMedsandMe/Reportum/3.0.0'
    description: Mock-V3.0
info:
  version: "3.0.0-oas3"
  title: MMM Reportum API
  description: MMM Reportum API
  contact:
    name: Daniele Galluccio
    email: daniele.galluccio@mymedsandme.com
security:
  - userKey: []
paths:
  /assets:
    get:
      parameters:
        - $ref: '#/components/parameters/brand'
        - $ref: '#/components/parameters/source'
        - $ref: '#/components/parameters/sourceversion'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema: {}
              example:
                logo: 'data:image/png;base64,iVBORw0KGgo...VORK5CYI='
                labels:
                  pt:
                    fr: francês
                    footer_url_2: 'https://www.reportum.com/'
                    confirmation_success_title: Obrigado. Nós realmente apreciamos o seu feedback.
                    confirmation_banner: Sucesso. Relatório completo
                    close_window: Janela fechada
                    overlay_ok_button: 'OK, entendi'
                    create_report: Crie um novo relatório
                    report_question: Não consegue encontrar o seu país / idioma? Clique aqui.
                    confirmation_button_download: Download do relatório (.PDF)
                    de: alemão
                    faq_strapline: Qual o proximo?
                    language: Língua
                    zh: Chinês
                    country_placeholder: por favor selecione seu país
                    language_placeholder: 'Por favor, selecione seu idioma'
                    faq:
                      '1':
                        question: Por que eu deveria ter mais de 18 anos?
                        answers:
                          - Você tem que ter mais de 18 anos
                          - Você é muito velho
                    footer_text: 'Obrigado por nos ajudar a tornar nossos produtos mais seguros e eficazes para todos, em qualquer lugar.'
                    languages:
                      zh: 中文
                      pt: Português
                      ja: 日本語
                      fr: Français
                      es: Español
                      en: English
                      de: Deutsche
                    home_banner: Bem vindo ao Reportum
                    copyright: Direito Autoral 2019 Bayer AG
                    confirmation_success_ref: 'Ref #:'
                    pt: Português
                    footer_link_1: Declaração de privacidade
                    footer_url_1: 'https://www.reportum.com/'
                    footer_link_2: Imprimir
                    confirmation_success_footer: 'Obrigado pelo seu relatório. Se for reservado, entraremos em contato se precisarmos de mais alguma informação.'
                    faq_header_text: ' '
                    confirmation_title: RELATÓRIO COMPLETO
                    confirmation_button_complete: Crie outro relatório
                    en: Inglês
                    header_strapline: Vamos começar.
                    es: espanhol
                    country: País
                    footer_url_3: 'https://www.reportum.com/'
                    report_question_link_text: Clique aqui.
                    footer_link_3: Termos de uso
                    title: Reportum
                    countries:
                      EH: Saara Ocidental*
                      TF: Territórios franceses do sul (the)
                      CU: Cuba
                      IS: Islândia
                      BY: Bielorrússia
                      YE: Iémen
                      SS: Sudão do Sul
                      TN: Tunísia
                      GU: Guam
                      CL: Chile
                      QA: Catar
                      SG: Cingapura
                      AD: Andorra
                      FK: 'Ilhas Falkland (the) [Malvinas]'
                      GD: Grenada
                      MK: Macedónia (ex-República jugoslava de)
                      AN: Antilhas holandesas
                      AF: Afeganistão
                      SM: São Marinho
                      VA: 'Santa Sé (o) [Estado da Cidade do Vaticano]'
                      SL: Serra Leoa
                    ja: japonês
                journeys:
                  - J001
                countryLanguages:
                  US:
                    - en
                    - es
                    - pt
                    - de
                    - fr
                    - zh
                    - ja
                  GB:
                    - en
                  DE:
                    - en
                    - de
        '500':
          description: Error
          content:
            application/json:
              schema: {}
      summary: Retrieve Assets for symposium-ui
  /journey/{ln}/{JID}:
    get:
      parameters:
        - $ref: '#/components/parameters/brand'
        - $ref: '#/components/parameters/source'
        - $ref: '#/components/parameters/sourceversion'
        - name: JID
          in: path
          description: ID of journey
          required: true
          schema:
            type: string
        - name: ln
          in: path
          description: ID of locale for the requested journey
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns a journey
          content:
            application/json:
              schema: {}
              example:
                  $ref: https://danielegalluccio.github.io/openapi-gui/reportum-api/v3.0.0/journey.json
  /reports:
    post:
      summary: submit a report
      parameters:
        - $ref: '#/components/parameters/brand'
        - $ref: '#/components/parameters/source'
        - $ref: '#/components/parameters/sourceversion'
      requestBody:
        content:
          application/json:
            schema: {}
            example:
              $ref: https://danielegalluccio.github.io/openapi-gui/reportum-api/v3.0.0/reports_request.json

        required: true
      responses:
        '201':
          description: item created
          headers:
        '422':
          description: UNPROCESSABLE ENTITY
          headers:
        '500':
          description: Generic internal error
          headers:
        default:
          description: An unexpected error occured.
          headers:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'



components:
  parameters:
    brand:
      name: m3-brand
      description: Client code. For example `mymeds` for test MyMedsAndMe brand.
      in: header
      required: true
      schema:
        type: string
    source:
      name: m3-source
      description: Type of client application, `symposium-ui` for symposium.
      in: header
      required: true
      schema:
        type: string
    sourceversion:
      name: m3-source-version
      description: Application version. .
      in: header
      required: true
      schema:
        type: string
  responses:
    StandardErrorResponse:
      description: An unexpected error occured.
      headers:
        X-Rate-Limit-Limit:
          description: The number of allowed requests in the current period
          schema:
            type: integer
        X-Rate-Limit-Remaining:
          description: The number of remaining requests in the current period
          schema:
            type: integer
        X-Rate-Limit-Reset:
          description: The number of seconds left in the current period
          schema:
            type: integer
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  securitySchemes:
    userKey:
      type: apiKey
      name: user_token
      in: header
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          $ref: '#/components/schemas/ErrorDetails'
    ErrorDetails:
      properties:
        fields:
          type: array
          items:
            type: string
        stacktrace:
          type: string
  links: {}
  callbacks: {}
